Map<String, String> textToGifMap = {
  '1':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F1.gif?alt=media',
  '2':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F2.gif?alt=media',
  '3':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F3.gif?alt=media',
  '5':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F5.gif?alt=media',
  '6':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F6.gif?alt=media',
  '7':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F7.gif?alt=media',
  '8':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F8.gif?alt=media',
  '9':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F9.gif?alt=media',
  'ألف':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FAlif.gif?alt=media',
  'أ':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FAlif.gif?alt=media',
  'ا':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FAlif.gif?alt=media',
  'ب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FBā.gif?alt=media',
  'ت':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FTāa.gif?alt=media',
  'ث':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FThā.gif?alt=media',
  'ج':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FJīm.gif?alt=media',
  'ح':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F%D9%8DḤā.gif?alt=media',
  'خ':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FKhā.gif?alt=media',
  'د':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FDāl.gif?alt=media',
  'ذ':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FDhāl.gif?alt=media',
  'ر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FRā.gif?alt=media',
  'ز':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FZay.gif?alt=media',
  'س':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FSīn.gif?alt=media',
  'ش':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FShīn.gif?alt=media',
  'ص':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FṢād.gif?alt=media',
  'ض':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F%D9%8DḌād.gif?alt=media',
  'ط':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FṬā.gif?alt=media',
  'ظ':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FẒā.gif?alt=media',
  'ع':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FAyn.gif?alt=media',
  'غ':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FGhayn.gif?alt=media',
  'ف':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FFā.gif?alt=media',
  'ق':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FQāf.gif?alt=media',
  'ك':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FKāf.gif?alt=media',
  'ل':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FLām.gif?alt=media',
  'م':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FMīm.gif?alt=media',
  'ن':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FNūn.gif?alt=media',
  'ه':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FHā.gif?alt=media',
  'و':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FWāw.gif?alt=media',
  'ي':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FYā.gif?alt=media',
  'أنا':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2F_ana.gif?alt=media',
  'عين':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FAyn.gif?alt=media',
  'باء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FBā.gif?alt=media',
  'ذال':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FDhāl.gif?alt=media',
  'دال':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FDāl.gif?alt=media',
  'فاء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FFā.gif?alt=media',
  'غين':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FGhayn.gif?alt=media',
  'هاء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FHā.gif?alt=media',
  'جيم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FJīm.gif?alt=media',
  'خاء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FKhā.gif?alt=media',
  'كاف':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FKāf.gif?alt=media',
  'لام':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FLām.gif?alt=media',
  'ميم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FMīm.gif?alt=media',
  'نون':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FNūn.gif?alt=media',
  'قاف':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FQāf.gif?alt=media',
  'راء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FRā.gif?alt=media',
  'شين':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FShīn.gif?alt=media',
  'سين':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FSīn.gif?alt=media',
  'ثاء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FThā.gif?alt=media',
  'تاء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FTā.gif?alt=media',
  'واو':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FWāw.gif?alt=media',
  'ياء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FYā.gif?alt=media',
  'زاي':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FZay.gif?alt=media',
  'ضاد':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F%D9%8DḌād.gif?alt=media',
  'حاء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2F%D9%8DḤā.gif?alt=media',
  'صاد':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FṢād.gif?alt=media',
  'طاء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FṬā.gif?alt=media',
  'ظاء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm%2FẒā.gif?alt=media',
  'انا':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2F_ana.gif?alt=media',
  'ابن':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fabn.gif?alt=media',
  'ابتياع':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fabtieath.gif?alt=media',
  'العال':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Falaealaa.gif?alt=media',
  'الاغتسال':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Falaightisal.gif?alt=media',
  'الإسفال':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Faliasfal.gif?alt=media',
  'الله':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fallah.gif?alt=media',
  'التشهد':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Faltashahud.gif?alt=media',
  'أنت':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fant.gif?alt=media',
  'أسامو':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fasamu.gif?alt=media',
  'ضغط':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fdaght.gif?alt=media',
  'هادي':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fhadi.gif?alt=media',
  'هيا':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fhuia.gif?alt=media',
  'إسعاف':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fiiseaf.gif?alt=media',
  'جامعة الحدود الشمالية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fjamieat_alhudud_lshamalia.gif?alt=media',
  'جانب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fjanib.gif?alt=media',
  'كلية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fkuliya.gif?alt=media',
  'كلو':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fkulu.gif?alt=media',
  'مشغول':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fmashghulil.gif?alt=media',
  'ممرضات':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fmumaridat.gif?alt=media',
  'مستشفى':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fmustashfaa.gif?alt=media',
  'صيدلية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Fsaydalia.gif?alt=media',
  'طبيب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Ftabib.gif?alt=media',
  'تعيبان':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Ftaeiban.gif?alt=media',
  'تحت':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm2%2Ftaht.gif?alt=media',
  'أنا سعيد بمعرفتك':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanm3%2Fana_saeid_maerifatuk.gif?alt=media',
  'العنت بخير':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fal_anat_bikhayr.gif?alt=media',
  'الإمارات':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Falamarat.gif?alt=media',
  'الحمد لله':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Falhamd_lilah.gif?alt=media',
  'الكويت':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Falkuayt.gif?alt=media',
  'الله أكبر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fallah_akbar.gif?alt=media',
  'المملكة العربية السعودية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Falmamlakat_alearabiat_alsueudia.gif?alt=media',
  'السلام عليكم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Falsalam_ealaykum.gif?alt=media',
  'اليمن':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Falyaman.gif?alt=media',
  'إن شاء الله':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fan_sha_allah.gif?alt=media',
  'أين المكان':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fayn_almakan.gif?alt=media',
  'بخير':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fbikhayr.gif?alt=media',
  'بريطانيا':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fbiritania.gif?alt=media',
  'إيمان':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Feamaan.gif?alt=media',
  'هذا':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fhadha.gif?alt=media',
  'هذا لطف منك':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fhadha%20latif%20mink.gif?alt=media',
  'هذا شيء للغاية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fhadha_si_lilghaya.gif?alt=media',
  'حزين':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fhazin.gif?alt=media',
  'كيف حالك':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fkayf_haluk.gif?alt=media',
  'كوريا الشمالية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fkuria%20alshamalia.gif?alt=media',
  'كوريا الجنوبية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fkuria_aljanubia.gif?alt=media',
  'لطيف':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Flatif.gif?alt=media',
  'ما اسمك':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fma_asmuk.gif?alt=media',
  'مساء الخير':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fmasa_alkhayr.gif?alt=media',
  'مصر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fmisr.gif?alt=media',
  'مساعدة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fmusaeida.gif?alt=media',
  'روسيا':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Frusia.gif?alt=media',
  'صباح الخير':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fsabah_alkhayr.gif?alt=media',
  'صباح النور':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fsabah_alnuwr.gif?alt=media',
  'يابان':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fanmk1%2Fyaban.gif?alt=media',
  'أب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fab.gif?alt=media',
  'أخذت عبير':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fakhidhat_abira.gif?alt=media',
  'ألم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Falm.gif?alt=media',
  'أشياء لزار':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fashieat_lizar.gif?alt=media',
  'استأذن إلي ذهب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fastadhan_eali_dhahab.gif?alt=media',
  'دعاء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fduea.gif?alt=media',
  'أدوية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Feadwaa.gif?alt=media',
  'عفواً':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Feafwan.gif?alt=media',
  'عملية جراحية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Feamaliat_jirahia.gif?alt=media',
  'عينات مختبر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Feayinat_mukhtabar.gif?alt=media',
  'حمى':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhamaa.gif?alt=media',
  'حساسية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhasasia.gif?alt=media',
  'حمل':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhumil.gif?alt=media',
  'معافى':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fmueafaa.gif?alt=media',
  'قلب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fqalb.gif?alt=media',
  'قمر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fqamar.gif?alt=media',
  'قرآن':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fquran.gif?alt=media',
  'رجم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Frajim.gif?alt=media',
  'شكرًا':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fshukran.gif?alt=media',
  'سكري':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fsukari.gif?alt=media',
  'تعال معي':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Ftaeal_maei.gif?alt=media',
  'أم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fum.gif?alt=media',
  'زكام':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fzukam.gif?alt=media',
  'أتمنى لك كل الشفاء العاجل':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Faitamanaa_lak_kulu_shifa_aleajil.gif?alt=media',
  'بن':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fbn.gif?alt=media',
  'عطشان':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Featshan.gif?alt=media',
  'حقيبة سفر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fhaqibat_safar.gif?alt=media',
  'جواز السفر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fjawaz_alsafar.gif?alt=media',
  'كتاب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fkitab.gif?alt=media',
  'موعد':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fmaweid.gif?alt=media',
  'نعاس':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fnueas.gif?alt=media',
  'قهوة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fqahwa.gif?alt=media',
  'قلم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fqalam.gif?alt=media',
  'سبورة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fsabura.gif?alt=media',
  'سفر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fsafar.gif?alt=media',
  'سلامات':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fsalamat.gif?alt=media',
  'طاولة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Ftawila.gif?alt=media',
  'طيب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Ftyb.gif?alt=media',
  'وردة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fwarada.gif?alt=media',
  'ظالم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fkhalid%2Fhhh%2Fzalim.gif?alt=media',
  'أبريل':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FApril.gif?alt=media',
  'أغسطس':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FAugust.gif?alt=media',
  'ديسمبر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FDecember.gif?alt=media',
  'فبراير':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FFebruary.gif?alt=media',
  'يناير':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FJanuary.gif?alt=media',
  'يوليو':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FJuly.gif?alt=media',
  'يونيو':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FJune.gif?alt=media',
  'مارس':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FMarch.gif?alt=media',
  'مايو':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FMay.gif?alt=media',
  'نوفمبر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FNovember.gif?alt=media',
  'أكتوبر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FOctober.gif?alt=media',
  'سبتمبر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmonths%2FSeptember.gif?alt=media',
  'رائد فضاء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2FAstronaut.gif?alt=media',
  'مجرة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2FGalaxy.gif?alt=media',
  'المريخ':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2FMars.gif?alt=media',
  'عطارد':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2FMercury.gif?alt=media',
  'نيزك':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2Fmeteor.gif?alt=media',
  'كوكب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2Fplanet.gif?alt=media',
  'زحل':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2FSaturn.gif?alt=media',
  'شهاب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2Fshihab.gif?alt=media',
  'فضاء شمسي':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2Fsolar_space.gif?alt=media',
  'أقمار صناعية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2FSpace_satellites.gif?alt=media',
  'مركبة فضائية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2FSpace_ship.gif?alt=media',
  'نجمة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fspace%2FStar.gif?alt=media',
  'مطار':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FAirport.gif?alt=media',
  'بنك':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FBank.gif?alt=media',
  'جميل':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FBeautiful.gif?alt=media',
  'استمارة_سيارة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FCar_form.gif?alt=media',
  'كمبيوتر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FComputer.gif?alt=media',
  'علوم_الحاسوب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FComputer_science.gif?alt=media',
  'فشل':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FFailed.gif?alt=media',
  'لا_يستطيع':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FHe_cant.gif?alt=media',
  'هو_يشرب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FHe_drinks.gif?alt=media',
  'هو_يسمع':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FHe_hears.gif?alt=media',
  'هو_يضحك':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FHe_laughs.gif?alt=media',
  'منطقة_الحدود_الشمالية':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FNorthern_border_region.gif?alt=media',
  'بشت':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FPasht.gif?alt=media',
  'سجود':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FProstration.gif?alt=media',
  'الرياض':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FRiyadh.gif?alt=media',
  'الطقس_جميل_اليوم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2FThe_weather_is_nice_today.gif?alt=media',
  'اعطني_رقمك':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2F_aetini_raqmak.gif?alt=media',
  'أنت_مبسوط':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2F_ant_mabsut.gif?alt=media',
  'اتحب_تناول_الاكل_عندي':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2F_atargheb_fi_tanawul_al_ukl_eindi.gif?alt=media',
  'ابشر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fabshar.gif?alt=media',
  'حادث':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Faccident.gif?alt=media',
  'اكل':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fakul.gif?alt=media',
  'اكل_حرام':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fakul_haram.gif?alt=media',
  'اكل_مال_اليتيم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fakul_mal_yatim.gif?alt=media',
  'اكل_طيبات':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fakul_tayibat.gif?alt=media',
  'اناناس':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fananas.gif?alt=media',
  'بطيخ':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fbatikh.gif?alt=media',
  'برتقال':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fburtuqal.gif?alt=media',
  'رخيص':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fcheap.gif?alt=media',
  'مدينة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fcity.gif?alt=media',
  'نقاش':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fdiscussion.gif?alt=media',
  'باب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fdoor.gif?alt=media',
  'فستان':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fdress.gif?alt=media',
  'اعطني_رقمك_مره_اخرى':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Featni_raqmak.gif?alt=media',
  'بيض':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fegg.gif?alt=media',
  'عنب':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Feinab.gif?alt=media',
  'عصفور':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Feusfur.gif?alt=media',
  'تين':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Ffig.gif?alt=media',
  'فراولة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Ffrawila.gif?alt=media',
  'تخرج':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fgraduation.gif?alt=media',
  'هل_ترغب_اكل_شيء':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fhal_targhab__akl_shay_.gif?alt=media',
  'صداع':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fheadache.gif?alt=media',
  'بيت':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fhouse.gif?alt=media',
  'جوال':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fjawaal.gif?alt=media',
  'كم_ساعة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fkam_saea.gif?alt=media',
  'كمثرى':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fkamuthraa.gif?alt=media',
  'مفتاح':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fkey.gif?alt=media',
  'خطبة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fkhuta.gif?alt=media',
  'كوكاكولا':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fkok.gif?alt=media',
  'كل_عام_وانت_بخير':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fkulu_eam_wanat_bikhayr.gif?alt=media',
  'كمبيوتر_شخصي':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fkumbuyutar.gif?alt=media',
  'كيوي':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fkywy.gif?alt=media',
  'محاضرة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Flecture.gif?alt=media',
  'لسان_عصفور':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Flisan_eusfur.gif?alt=media',
  'مدينة_الملاهي':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fmadinat_almalahi.gif?alt=media',
  'مانجا':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fmanja.gif?alt=media',
  'موز':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fmawz.gif?alt=media',
  'نعاس':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fnueas.gif?alt=media',
  'قديم':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fold.gif?alt=media',
  'سيارة شرطة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fpolice_car.gif?alt=media',
  'رامان':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Framan.gif?alt=media',
  'نهر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Friver.gif?alt=media',
  'طريق':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Froad.gif?alt=media',
  'ساعة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fsaea.gif?alt=media',
  'عاقل':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fsane.gif?alt=media',
  'بحر':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fsea.gif?alt=media',
  'شمام':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fshamam.gif?alt=media',
  'الأول':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fthe_first.gif?alt=media',
  'الثاني':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fthe_second.gif?alt=media',
  'تين':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Ftin.gif?alt=media',
  'تفاح':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Ftufaah.gif?alt=media',
  'توت':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Ftut.gif?alt=media',
  'عطلة':
      'https://firebasestorage.googleapis.com/v0/b/asl-arabic.appspot.com/o/animation%2Fmmm%2Fvacation.gif?alt=media',
};
